# Generated by Django 3.2.6 on 2021-11-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('doboard', models.DateField(blank=True, null=True)),
                ('doarrival', models.DateField(blank=True, null=True)),
                ('transc_amount', models.IntegerField()),
                ('trans_date', models.DateField()),
                ('is_cancelled', models.BooleanField()),
                ('train_no', models.ForeignKey(db_column='train_no', on_delete=django.db.models.deletion.DO_NOTHING, to='trains.train')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_gender', models.CharField(blank=True, max_length=6, null=True)),
                ('p_age', models.IntegerField()),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.ticket')),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('train_no', models.IntegerField()),
                ('is_cancelled', models.BooleanField()),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.passenger')),
            ],
            options={
                'db_table': 'seat',
                'unique_together': {('seat_no', 'train_no')},
            },
        ),
    ]
