# Generated by Django 3.2.8 on 2021-11-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='is_cancelled',
            field=models.BooleanField(default=True),
        ),
    ]
