# Generated by Django 3.2.8 on 2021-11-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.TextField(max_length=25),
        ),
    ]
