# Generated by Django 3.2.8 on 2021-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userdata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='wallet',
            field=models.IntegerField(default=2000),
        ),
    ]
